cp /usr/bin/mcconsole ./root/usr/bin/mcconsole
cp /usr/bin/mclogs ./root/usr/bin/mclogs
cp /usr/bin/mcbackup ./root/usr/bin/mcbackup
cp /usr/bin/mchelp ./root/usr/bin/mchelp
cp /usr/bin/mcsend ./root/usr/bin/mcsend
cp /usr/bin/tpsend ./root/usr/bin/tpsend
cp /usr/bin/mcstart ./root/usr/bin/mcstart
cp /usr/bin/bpconsole ./root/usr/bin/bpconsole
cp /usr/bin/bpdelete ./root/usr/bin/bpdelete
cp /usr/bin/bplist ./root/usr/bin/bplist
cp /usr/bin/bpload ./root/usr/bin/bpload
cp /usr/bin/bpstart ./root/usr/bin/bpstart
cp /usr/bin/tpconsole ./root/usr/bin/tpconsole
cp /usr/bin/tplogs ./root/usr/bin/tplogs
cp /usr/bin/tpstart ./root/usr/bin/tpstart
cp /usr/bin/mc_module.py ./root/usr/bin/
cp /usr/bin/mcfirstjoins ./root/usr/bin/
cp /home/minecraft/server/start.sh ./root/home/minecraft/server/start.sh
cp /home/minecraft/server/stinfo.yaml ./root/home/minecraft/server/stinfo.yaml
#cp /home/minecraft/palgania_save/push_oby.py ./root/home/minecraft/palgania_save/push_oby.py
#cp /home/minecraft/palgania_save/save.sh ./root/home/minecraft/palgania_save/save.sh
#cp /home/minecraft/palgania_save/encrypt.py ./root/home/minecraft/palgania_save/encrypt.py
cp /home/minecraft/limoncello/modules/interact_server.py ./root/home/minecraft/limoncello/modules/
cp /usr/bin/botstart ./root/usr/bin/botstart
cp -r /home/minecraft/ftp ./root/home/minecraft/
cp /home/minecraft/rshell/commands.py root/home/minecraft/rshell/
